---
title: "JSM 2020 Abstract"
author: "Katherine Goode"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

*To submit a session abstract, you will need the following:*

**Session Type (Contributed, Topic-Contributed, Roundtable)**

Contributed

**Session Subtype (Paper, Speed, Poster, A.M. or P.M. Roundtable)**

Paper

**Primary Sponsor (ASA Committee, ASA Section, JSM Sponsoring Society). A pull-down screen with a pre-approved list is provided.**

Section on Statistical Learning and Data Science 

**Abstract Title**

Using Trees to Interpret Random Forests

**Abstract Text (1,200-character limit)**

Random forests are a commonly used machine learning models in prediction problems. However, the ability to explain a prediction produced by a random forest is limited. We will present two methods we have developed that use regression/classification trees to explain predictions made by random forests.

**Abstract Keywords**

Random Forests, Interpretability, Explainability, Trees

**Presenting author and co-author contact information. Please note, there can only be one presenting author. Accurate and unique email addresses are required for all authors or records may be merged.**

Katherine Goode kgoode@iastate.edu (presenting author)  
Heike Hofmann hofmann@iastate.edu

**Note whether the abstract can be considered for alternate session subtypes. The program committee will not have space for all paper abstracts received. Acceptance is more likely if the presentation can be made in different session formats.**

No