---
title: "JSM Abstract"
author: "Katherine Goode"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

### To submit a session abstract, you will need the following:

#### Session Type (Contributed, Topic-Contributed*, Roundtable)

Contributed

#### Session Subtype (Paper, Speed, Poster, A.M. or P.M. Roundtable)

Paper

#### Primary Sponsor (ASA Committee, ASA Section, JSM Sponsoring Society). A pull-down screen with a pre-approved list is provided.

- the section on statistical learning and data science 
- maybe the section on statistical computing

#### Abstract Title

Visual Diagnostics of a Model Explainer: Tools for the Assessment of LIME Explanations from Random Forests

#### Abstract Text (1200 character limit)

Random forests are known for their accurate predictive abilities, but they are a part of the family of machine learning models that lack interpretability. A technique called LIME was developed to provide local interpretations for predictive models. The technique fits a ridge regression model to binary encoded perturbations created from the observed data weighted by proximity to the  prediction of interest. The predicted values associated with the perturbations computed using the complex model are used as the response variable in the regression. The coefficients from the linear model are then used to determine the influential variables. We have developed some visualizations and other diagnostic tools to assess the explanations produced by LIME from a random forest. In particular, we consider how well the simple model fit by LIME captures the random forest model and how the results from LIME vary based on different algorithm input options. To demonstrate these tools, we apply LIME to a random forest fit to a forensics bullet matching dataset using the lime R package and apply our methods to diagnose the LIME explanations.

#### Abstract Keywords

random forest, LIME, black box model, interpretability, diagnostics

#### Presenting author and co-author contact information. Please note, there can only be one presenting author. Accurate and unique email addresses are required for all authors.

Presenting author: Katherine Goode <kgoode@iastate.edu>

Co-author: Heike Hofmann <hofmann@iastate.edu>

#### Note:

- If the abstract can be considered for alternate session subtypes. The program committee will not have space for all paper abstracts received. Acceptance is more likely if the presentation can be made in different session formats.
- Information on abstract submission from: http://ww2.amstat.org/meetings/jsm/2019/submissions.cfm 

#### Revisions

You may revise your abstract text, title, and keywords or add coauthors from December 3, 2018, through February 4, 2019, and April 1 through April 18, 2019.

#### Proof of Progress

All presenters must send proof of a paper in progress to the appropriate JSM session chair by May 17, 2019. Proof of a paper in progress can be a draft manuscript, detailed outline, PowerPoint slides, etc. If you do not send the required proof, your paper may be deleted from the program and become ineligible for publication in the JSM Proceedings. This requirement applies to all contributed and topic-contributed speakers and invited sessions with discussants.